### ISSUE TITLE
Problema na grid

### ISSUE THREAD

**Issue by gabrielpoca** [U-Play/profiles#22]
@naps62 no [grid](https://github.com/U-Play/profiles/blob/dev/app/assets/stylesheets/grid.sass) tem isto 

```
.profile-edit
  +grid-row()
  +grid-column($columns: 11, $offset: 1)
  form
    margin: 0
```

apercebi-me ao fazer rebase. Foi propositado o ter um row e columns no mesmo? Funciona?

**Comment by naps62** [comment]
foi +/- propositado
funcionou pelo menos para esse caso, mas também achei estranho na altura. Foi mais para tentar evitar fazer um wrapper a volta so por causa disso

**Comment by gabrielpoca** [comment]
Mas será que isso não tem problemas? Que se der realmente para usar assim sem haver problemas podia poupar dar muitos nomes a coisas realmente. Ainda que ande a tentar escrever html mais semantico e focar conteudo o facto de ser preciso wrappers obriga-me a inserir elementos que servem apenas para estilo, mas se assim funciona era nice. Tenho de investigar

**Comment by naps62** [comment]
do que eu testei, pelo menos naquele caso não deu problemas. Mas é questão de tentar
