### ISSUE TITLE
cuidado com as migrações

### ISSUE THREAD

**Issue by naps62** [U-Play/profiles#38]
@gabrielpoca o pull request que fizeste merge á bocado deu-me problemas a mim. acho que era por causa de estares a criar campos novos com `null: false` em tabelas já existentes.

não sei se sabias disso a partida, ou se é limitação do sqlite, e se em postgres não acontece, mas fica aqui o aviso, que convem ter cuidado com isto. fui obrigado a fazer drop da BD

**Comment by gabrielpoca** [comment]
@naps62 Eu sei, na altura que fiz até o side show estava comigo. Ali não tinha outra hipótese porque o que acontece é que um desses campos não só tem `null: false` como tem `unique: true`, nesta altura não corremos perigo de perder nada por este tipo de operação.

**Comment by naps62** [comment]
não disse que corrias risco de perder coisas. o que aconteceu foi que não consegui fazer migrate, pelo que percebi, porque ele não sabia o que fazer a essas colunas nos registos que já existiam

mas do que vi isto é so problema do sqlite: `The ALTER TABLE command in SQLite allows the user to rename a table or to add a new column to an existing table. It is not possible to rename a column, remove a column, or add or remove constraints from a table`

**Comment by gabrielpoca** [comment]
Hum, mas acho que não foi disso, pelo menos no meu caso, o problema era ter ja utilizadores na base de dados e ao fazer alterações esses utilizadores não tinha valores para aquelas colunas, e como tal a coluna que não tem valor default deu erro. Nem estava relacionado com isso o que me aconteceu.

**Comment by naps62** [comment]
ahhh, nao tinha reparado que tinhas um campo null sem default.
mas então isso não é má ideia? porque não permitir que seja null simplesmente? depois podias fazer override ao getter para o definir se ele ainda não existisse

**Comment by gabrielpoca** [comment]
Também pode ser. A ideia era que este campo seja único e exista sempre. Assim não há necessidade na aplicação verificar se existe. Basicamente isto é usado para criar referrals (por agora pelo menos). Se existir a hipotese de ser null então tem de se verificar se há escaxe ou não em algum lado. Assim garante-se que que funciona sempre. Depois no model tenho um before que gera um random para preencher esse campo.
