### ISSUE TITLE
Converter o link do facebook e do twitter para username.

### ISSUE THREAD

**Issue by gabrielpoca** [U-Play/profiles#83]
Eu estava a pensar na questão de transformar os links do facebook/twitter em usernames independetemente do input do utilizador (já tinhamos discutido isto). O utilizador insere o link ou o username, se for um link tem de se converter para username. A minha questão aqui é sobre a melhor maneira, eu tenho duas sugestões:
### Utilizar os models

Criar um filtro/callback before_save (por exemplo) que sempre que se for criar/actualizar um utilizador é executado.
### Utilizar um service object

Neste caso teria de haver um service object que seria sempre responsável por actualizações a um user. O problema disto é que onde quer que seja que se tente actualizar um user teria de utilizar este service. Isto seria um problema porque os restantes models não tem esta camada de separação.

Portanto an minha opinião é a primeira opção. @naps62 @azevedo-252 chutem.

**Comment by adrianoapmartins** [comment]
até que enfim pah

**Comment by gabrielpoca** [comment]
@ampyka ahahah :P já estava a incomodar na lista xd
